/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projeto_gcms;

public class Library {
    public boolean someLibraryMethod() {
    	System.out.println("mostrando detalhes");
    	System.out.println("teste");
        return false;
    }
}
